name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Some task that fetches dependencies
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ./fetch-deps.sh
      # - name: Create SSH key
      #   env:
      #     SSH_PRIVATE_KEY: ${{secrets.GITHUB_TOKEN}}
      #   run: |
      #     echo "$SSH_PRIVATE_KEY" > private.key
      #     sudo chmod 400 private.key
      
      # - name: Docker Dependencies
      #   run: |
      #       eval `ssh-agent -s`
      #       ssh-add private.key
      # - name: Start ssh-agent and add SSH key
      #   env:
      #     ssh-private-key: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #    eval "$(ssh-agent -s)"
      #    echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

      # - name: Setup SSH Key
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.GITHUB_TOKEN }}          

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:SurendraR/surendrar.github.io.git
          npm run deploy # Or your custom deploy command
